#!/usr/bin/env bash

set -e

WORK_DIR=/usr/src

function handle_error() {
  local status=$?
  if [[ $status > 0 ]]; then
    echo "🔥 There was a problem building the binary. Operation aborted."
    exit 1
  fi
}
trap handle_error EXIT SIGINT

# avoid error: E: You must put some 'deb-src' URIs in your sources.list
echo "deb-src http://archive.ubuntu.com/ubuntu noble main universe" >> /etc/apt/sources.list



echo "⚙️ Getting libraries and dependencies..."
apt-get update -y
apt-get install -y build-essential autoconf libtool git-core
apt-get build-dep -y imagemagick libmagickcore-dev

# get, configure and install imagemagick
echo "⚙️ Installing imagemagick version 7.0.11-5..."
git clone --depth 1 --branch 7.0.11-5 https://github.com/ImageMagick/ImageMagick.git $WORK_DIR/imagemagick
cd $WORK_DIR/imagemagick
./configure --with-heic=yes --prefix=$WORK_DIR/imagemagick --without-gvc
make && make install


# clean up the build and get ready for packaging
echo "🧹 Cleaning up..."
strip lib/*.a lib/lib*.so*

# compress the binary
echo "🗄️ Compressing build..."
rm -rf build
mkdir build
tar czf $WORK_DIR/imagemagick/build/imagemagick.tar.gz bin include lib

# copy the compressed file/tarball from the docker container into the repo
cp $WORK_DIR/imagemagick/build/imagemagick.tar.gz /buildpack/build/$1

echo "✅ All done!"
